Libreria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('chaining/', include('smart_selects.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

app/urls.py
from django.urls import path
from .views import *
from app.controller import cart, checkout, orden

urlpatterns = [
    path('',            home,       name="home"),
    path('contacto/',   contacto,   name="contacto"),
    path('galeria/',    galeria,    name="galeria"),
    path('agregar-producto/',    agregar_producto,    name="agregar_producto"),
    path('listar-productos/',    listar_productos,    name="listar_productos"),
    path('modificar-producto/<id>/',    modificar_producto,    name="modificar_producto"),
    path('eliminar-producto/<id>/',    eliminar_producto,    name="eliminar_producto"),
    path('detalle-producto/<int:pk>/',    DetalleLibro.as_view(),    name="detalle_libro"),
    path('agregar-tienda/',    agregar_tienda,    name="agregar_tienda"),
    path('listar-tiendas/',    listar_tiendas,    name="listar_tiendas"),
    path('modificar-tienda/<id>/',    modificar_tienda,    name="modificar_tienda"),
    path('recoger-tienda/',    recoger_tienda,    name="recoger_tienda"),
    path('eliminar-tienda/<id>/',    eliminar_tienda,    name="eliminar_tienda"),
    path('agregar-existencias/<id>/<id2>/',    agregar_existencias,    name="agregar_existencias"),
    path('aumentar-existencias/<id>/<id2>/<id3>',    aumentar_existencias_t,    name="aumentar_existencias"),
    path('eliminar-existencias/<id>/<id2>/<id3>',    eliminar_existencias_t,    name="eliminar_existencias"),
    path('listar-existencias/<id>/',    listar_existencias,    name="listar_existencias"),
    path('escoger-existencia/<id>/',    escoger_existencias,    name="escoger_existencia"),
    path('registro/',    registro,    name="registro"),
    path('ver-perfil/',    ver_perfil,    name="ver_perfil"),
    path('modificar-perfil/',    modificar_perfil,    name="modificar_perfil"),
    path('eliminar-perfil/<int:pk>/',    eliminar_perfil.as_view(),    name="eliminar_perfil"),
    path('cambiar-contraseña',    cambiar_contrasenia.as_view(),    name="cambiar_contraseña"),
    path('add-to-cart', cart.addtocart, name="addtocart"),
    path('cart', cart.viewcart, name="cart"),
    path('update-cart', cart.updatecart, name="updatecart"),
    path('delete-cart-item', cart.deletecartitem, name="deletecartitem"),
    path('checkout', checkout.index, name="checkout"),
    path('checkout-tienda/<id>/', checkout_tienda, name="checkout_tienda"),
    path('checkout-tienda-orden/<id>/', checkout_tienda_orden, name="checkout_tienda_orden"),
    path('placerorder', checkout.placeorder, name="placeorder"),
    path('listar-tarjetas/',    listar_tarjetas,    name="listar_tarjetas"),
    path('agregar-saldo/<id>',    agregar_saldo,    name="agregar_saldo"),
    path('eliminar-tarjeta/<id>',    eliminar_tarjeta,    name="eliminar_tarjeta"),
    path('tarjeta/',    tarjeta,    name="tarjeta"),
    path('forum/', forums, name="forum"),
    path('addInForum/',addInForum,name='addInForum'),
    path('addInDiscussion/<id>/',addInDiscussion,name='addInDiscussion'),
    path('mapa/',    mapa,    name="mapa"),
    path('listar-noticias/', listar_noticias, name="listar_noticias"),
    path('eliminar-noticia/<id>/', eliminar_noticia, name="eliminar_noticia"),
    path('mis-ordenes/', orden.index , name="ordenes"),
    path('ver-orden/<str:t_no>/', orden.verorden , name="verorden"),
    path('cancelar-orden/<str:t_no>/', orden.cancelar_orden , name="cancelar_orden"),
    path('realizar-devolucion/<str:t_no>/', orden.realizar_devolucion , name="realizar_devolucion"),
    path('add-to-cart-reserva', cart.addtocartReserva, name="addtocartreserva"),

    path('reservar-libro', cart.RegistrarReserva , name="reservar_libro"),
    path('ver-reserva', cart.viewreserva , name="ver_reserva"),
    path('delete-reserva-item', cart.deletereservaitem, name="deletereservaitem"),

]

app/models.py
from ast import Delete
from distutils.command.upload import upload
from random import choices
from django.db import models
from django.contrib.auth.models import User
from multiselectfield import MultiSelectField
from django_countries.fields import CountryField
from django.core.validators import MaxValueValidator
from cities_light.models import Country, Region, City
from smart_selects.db_fields import ChainedForeignKey
# Create your models here.
GENEROS_PREFERENCIA = ((1, 'Accion'),
              (2, 'Aventura'),
              (3, 'Terror'),
              (4, 'Ciencia Ficcion'),
              (5, 'Romance'),
              (6, 'Humor'),
              (7, 'Poesia'),
              (8, 'Novela'))

DIAS_SEMANA = ((1, 'Lunes'),
              (2, 'Martes'),
              (3, 'Miercoles'),
              (4, 'Jueves'),
              (5, 'Viernes'),
              (6, 'Sabado'),
              (7, 'Domingo'))

class Editorial(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre

class Producto(models.Model):
    nombre =                models.CharField(max_length=50)
    precio =                models.IntegerField()
    autor =                 models.CharField(max_length=50)
    genero =                models.IntegerField(choices=GENEROS_PREFERENCIA)
    num_paginas=            models.IntegerField()
    descripcion =           models.TextField()
    nuevo =                 models.BooleanField()
    editorial =             models.ForeignKey(Editorial, on_delete=models.PROTECT)
    fecha_fabricacion =     models.DateField()
    issn=                   models.IntegerField(unique = True)
    imagen =                models.ImageField(upload_to="productos", null=True)
    quantity =              models.IntegerField(null=True)

    def __str__(self):
        return self.nombre

opciones_consulta =[
    [0, "consulta"],
    [1, "reclamo"],
    [2, "sugerencia"],
    [3, "felicitaciones"],
]
class Tienda (models.Model):
    nombre =                models.CharField(max_length=50)
    dias_atencion =         MultiSelectField(choices=DIAS_SEMANA,max_length=100)
    telefono =              models.IntegerField()
    horario_apertura =      models.TimeField()
    horario_cierre =        models.TimeField()

    def __str__(self):
        return self.nombre

class Carrito (models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    product = models.ForeignKey(Producto, on_delete = models.CASCADE)
    producto_qty = models.IntegerField(null=False, blank = False)
    created_at = models.DateTimeField(auto_now_add = True)

class Existencias(models.Model):
    producto = models.ForeignKey(Producto, on_delete = models.CASCADE)
    tienda = models.ForeignKey(Tienda, on_delete = models.CASCADE)
    existencias= models.IntegerField(null= True)


class Contacto(models.Model):
    nombre = models.CharField(max_length=50)
    correo = models.EmailField()
    tipo_consulta = models.IntegerField(choices=opciones_consulta)
    mensaje = models.TextField()
    avisos = models.BooleanField()

    def __str__(self):
        return self.nombre

GENEROS_PREFERENCIA = ((1, 'Accion'),
              (2, 'Aventura'),
              (3, 'Terror'),
              (4, 'Ciencia Ficcion'),
              (5, 'Romance'),
              (6, 'Humor'),
              (7, 'Poesia'),
              (8, 'Novela'))

GENERO =(
    (1, "Masculino"),
    (2, "Femenino"),
    (3, "No binario"),
)
class PerfilUsuario(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    DNI = models.PositiveIntegerField(primary_key=True, unique=True,validators=[MaxValueValidator(9999999999)])
    telefono = models.IntegerField()
    genero=models.IntegerField(choices=GENERO)
    fecha_nacimiento = models.DateField()
    pais = models.ForeignKey(Country, on_delete=models.CASCADE, null=True)
    departamento = ChainedForeignKey(Region, chained_field="pais", chained_model_field="country", null=True)
    ciudad = ChainedForeignKey(City, chained_field="departamento", chained_model_field="region", null=True)
    generos_preferencia = MultiSelectField(choices=GENEROS_PREFERENCIA,max_length=100,null=True,blank=True)
    direccion_correspondencia = models.CharField(max_length=100, null=True,blank=True)
    foto_perfil = models.ImageField(upload_to="fotoperfil", null=True, blank=True)

    def __str__(self):
        return self.user.username

class Tarjeta(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    num_tarjeta = models.IntegerField()
    nombre_propietario = models.CharField(max_length=50,null=True)
    mes_exp = models.IntegerField()
    year_exp = models.IntegerField()
    cvv = models.IntegerField()
    saldo = models.IntegerField()

class forum(models.Model):
    user= models.ForeignKey(User,on_delete=models.CASCADE, null=True)
    tema= models.CharField(max_length=300)
    descripcion = models.CharField(max_length=1000,blank=True)
    date_created=models.DateTimeField(auto_now_add=True,null=True)
    

class noticia(models.Model):
    producto=               models.ForeignKey(Producto, on_delete=models.CASCADE)
    descripcion =           models.TextField(null=True,blank=True)
    fecha_publicacion =     models.DateTimeField(auto_now_add=True, null=True)


#child model
class Discussion(models.Model):
    forum = models.ForeignKey(forum,blank=True,on_delete=models.CASCADE)
    discuss = models.CharField(max_length=1000)
    user= models.ForeignKey(User,on_delete=models.CASCADE, null=True)

class Orden(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    fname=models.CharField(max_length=150, null=True)
    lname=models.CharField(max_length=150, null=True)
    email=models.CharField(max_length=150, null=True)
    celular=models.CharField(max_length=150, null=True)
    direccion=models.TextField( null=True)
    pais=models.CharField(max_length=150, null=True)
    ciudad=models.CharField(max_length=150, null=True)
    dni=models.CharField(max_length=150, null=True)
    fecha_nacimiento=models.CharField(max_length=150, null=True)
    precio_total = models.FloatField(null=True)
    forma_pago = models.CharField(max_length=150, null=True)
    forma_pago_id = models.CharField(max_length=150, null=True)
    statusdeorden = {
        ('Pendiente','Pendiente'),
        ('En envio','En envio'),
        ('Completado','Completado'),
        ('Cancelada','Cancelada'),
        ('Devuelta','Devuelta'),
        
    }
    estatus = models.CharField(max_length=150,choices=statusdeorden,default ='Pendiente')
    mensaje =models.TextField( null=True)
    seguimiento_num = models.CharField(max_length=150, null=True)
    creado_en = models.DateTimeField(auto_now_add=True)
    actualizado_en = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{} - {}'.format(self.id, self.seguimiento_num)

class OrdenItem(models.Model):
    orden = models.ForeignKey(Orden, on_delete = models.CASCADE)
    producto =models.ForeignKey(Producto, on_delete = models.CASCADE)
    precio = models.FloatField(null=True)
    cantidad = models.IntegerField(null=True)

    def __str__(self):
        return '{} - {}'.format(self.orden.id, self.orden.seguimiento_num)

class Reserva(models.Model):
    product = models.ForeignKey(Producto, on_delete = models.CASCADE)
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    cantidad_dias = models.SmallIntegerField('Cantidad de dias a reservar',default=1)
    fecha_creacion = models.DateField(auto_now_add=True)
    cantidad_producto= models.IntegerField(null=True)
    estado = models.BooleanField(default=True,verbose_name='Estado')

app/templates/app/perfil/cambiarcontraseña.html
{% extends 'app/base.html' %}

{% block contenido %}
<h2>Cambiar Contraseña</h2>
<form action="" method="POST" class="ui form">
    {% csrf_token %}
    {{form.as_p}}
    <button type="submit" class="btn btn-primary">Cambiar Contraseña</button>      


</form>

{% endblock %}

app/templates/app/perfil/eliminarperfil.html
{% extends 'app/base.html' %}

{% block contenido %}
<h2>Eliminar perfil</h2>
<form method="post">
    {% csrf_token %}
    <p>¿Estás seguro de que quieres eliminar el usuario {{ object.username }}?</p>
    <table>
        <tr>
            <button type="submit" class="btn btn-primary">Si, quiero eliminar mi cuenta</button>      
            <a href="{% url 'ver_perfil' %}" class="btn btn-danger">No</a>
            
        </tr>
    </table>
    
</form>

{% endblock %}

app/templates/app/perfil/modificarperfil.html
{% extends 'app/base.html' %}

{% block contenido %}

{% load crispy_forms_tags %}
<br>
<div class="row">
    <div class="col-12 col-md-6 offset-md-3">

        <div class="card">
            <div class="card-body">
                <h2>Editar Perfil</h2>
                <hr>
            <form action="" method="post" enctype="multipart/form-data">

                {% csrf_token %}
                {{ perfil_form.media.js }}
                {{ form | crispy }}
                {{ perfil_form | crispy }}

                <br>
                <div class="d-flex justify-content-left">
                    <input type="submit" value="Editar" class="btn btn-primary">
                    &nbsp;
                    &nbsp;
                    &nbsp;
                    <input type="reset" value="Cancelar" class="btn btn-secondary">
                    

                </div>
                
            </form>
            {{ mensaje }}

        </div>
    </div>

  </div>
</div>

{% endblock %}

app/templates/app/perfil/verperfil.html
{% extends 'app/base.html' %}

{% block contenido %}
{% if user.is_authenticated %}

<div style="display: flex; align-items: center;">
    <table class="table caption-top mt-5 table-bordered border-secondary
                table-light table-hover">
        <caption>
            PERFIL DE: {{user | title }}
        </caption>
        <tr>
            <th>Usuario</th>
            <td>{{user | title }}</td>
        </tr>
        <tr>
            <th>Nombre</th>
            <td>{{user.first_name | title }}</td>
        </tr>
        <tr>
            <th>Apellidos</th>
            <td>{{user.last_name | title }}</td>
        </tr>
        <tr>
            <th>Correo</th>
            <td>{{user.email | lower }}</td>
        </tr>
        <tr>    
            <th>Contraseña</th>
            <td> ******** </td>
        </tr>
        <tr>
            <th>DNI</th>
            <td>{{user.perfilusuario.DNI | title }}</td>
        </tr>
        <tr>
            <th>Telefono</th>
            <td>{{user.perfilusuario.telefono | title }}</td>
        </tr>
        <tr>
            <th>Genero</th>
            <td>{{user.perfilusuario.get_genero_display | title }}</td>
        </tr>
        <tr>
            <th>Fecha de Nacimiento</th>
            <td>{{user.perfilusuario.fecha_nacimiento | date:"d F Y"  }}</td>
        </tr>
        
        <tr>
            <th>Ciudad de Nacimiento</th>
            <td>{{user.perfilusuario.ciudad | title }}</td>
        </tr>
        {% if request.user.groups.all.0.name == "Cliente" %}
        <tr>
            <th>Generos de preferencia</th>
            <td>{{user.perfilusuario.generos_preferencia | title }}</td>
        </tr>
        {% endif %}
        {% if request.user.groups.all.0.name == "Cliente" %}
        <tr>
            <th>Direccion</th>
            <td>{{user.perfilusuario.direccion_correspondencia | title }}</td>
        </tr>
        {% endif %}
    </table>

   <td><img src="{{ user.perfilusuario.foto_perfil.url }}" style="height:16rem; width: 18rem; border: 2px solid rgb(90, 90, 90); margin-left: 20px;"></td> 
        
</div>

<table>
    <tr>      
        <a href="{% url 'modificar_perfil'  %}" class="btn btn-primary m-1">Modificar</a>
        <a href="{% url 'cambiar_contraseña'  %}" class="btn btn-primary m-1">Modificar contraseña</a>
        <a href="{% url 'eliminar_perfil' request.user.id %}" class="btn btn-danger m-1">Eliminar</a>
        {% if request.user.groups.all.0.name == "Cliente" %}
        <a href="{% url 'listar_tarjetas' %}" class="btn btn-warning m-1">Ver Tarjetas</a>
        <a href="{% url 'ordenes' %}" class="btn btn-success m-1">Mis compras</a>
        
        {% endif %}
        
    </tr>
</table>
{% else %}
<p> Inicia sesion para ver los detalles</p>
{% endif %}
{% endblock %}