Libreria/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('app.urls')),
    path('accounts/',include('django.contrib.auth.urls')),
    path('chaining/', include('smart_selects.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

app/urls.py
from django.urls import path
from .views import *
from app.controller import cart, checkout, orden

urlpatterns = [
    path('',            home,       name="home"),
    path('contacto/',   contacto,   name="contacto"),
    path('galeria/',    galeria,    name="galeria"),
    path('agregar-producto/',    agregar_producto,    name="agregar_producto"),
    path('listar-productos/',    listar_productos,    name="listar_productos"),
    path('modificar-producto/<id>/',    modificar_producto,    name="modificar_producto"),
    path('eliminar-producto/<id>/',    eliminar_producto,    name="eliminar_producto"),
    path('detalle-producto/<int:pk>/',    DetalleLibro.as_view(),    name="detalle_libro"),
    path('agregar-tienda/',    agregar_tienda,    name="agregar_tienda"),
    path('listar-tiendas/',    listar_tiendas,    name="listar_tiendas"),
    path('modificar-tienda/<id>/',    modificar_tienda,    name="modificar_tienda"),
    path('recoger-tienda/',    recoger_tienda,    name="recoger_tienda"),
    path('eliminar-tienda/<id>/',    eliminar_tienda,    name="eliminar_tienda"),
    path('agregar-existencias/<id>/<id2>/',    agregar_existencias,    name="agregar_existencias"),
    path('aumentar-existencias/<id>/<id2>/<id3>',    aumentar_existencias_t,    name="aumentar_existencias"),
    path('eliminar-existencias/<id>/<id2>/<id3>',    eliminar_existencias_t,    name="eliminar_existencias"),
    path('listar-existencias/<id>/',    listar_existencias,    name="listar_existencias"),
    path('escoger-existencia/<id>/',    escoger_existencias,    name="escoger_existencia"),
    path('registro/',    registro,    name="registro"),
    path('ver-perfil/',    ver_perfil,    name="ver_perfil"),
    path('modificar-perfil/',    modificar_perfil,    name="modificar_perfil"),
    path('eliminar-perfil/<int:pk>/',    eliminar_perfil.as_view(),    name="eliminar_perfil"),
    path('cambiar-contraseña',    cambiar_contrasenia.as_view(),    name="cambiar_contraseña"),
    path('add-to-cart', cart.addtocart, name="addtocart"),
    path('cart', cart.viewcart, name="cart"),
    path('update-cart', cart.updatecart, name="updatecart"),
    path('delete-cart-item', cart.deletecartitem, name="deletecartitem"),
    path('checkout', checkout.index, name="checkout"),
    path('checkout-tienda/<id>/', checkout_tienda, name="checkout_tienda"),
    path('checkout-tienda-orden/<id>/', checkout_tienda_orden, name="checkout_tienda_orden"),
    path('placerorder', checkout.placeorder, name="placeorder"),
    path('listar-tarjetas/',    listar_tarjetas,    name="listar_tarjetas"),
    path('agregar-saldo/<id>',    agregar_saldo,    name="agregar_saldo"),
    path('eliminar-tarjeta/<id>',    eliminar_tarjeta,    name="eliminar_tarjeta"),
    path('tarjeta/',    tarjeta,    name="tarjeta"),
    path('forum/', forums, name="forum"),
    path('addInForum/',addInForum,name='addInForum'),
    path('addInDiscussion/<id>/',addInDiscussion,name='addInDiscussion'),
    path('mapa/',    mapa,    name="mapa"),
    path('listar-noticias/', listar_noticias, name="listar_noticias"),
    path('eliminar-noticia/<id>/', eliminar_noticia, name="eliminar_noticia"),
    path('mis-ordenes/', orden.index , name="ordenes"),
    path('ver-orden/<str:t_no>/', orden.verorden , name="verorden"),
    path('cancelar-orden/<str:t_no>/', orden.cancelar_orden , name="cancelar_orden"),
    path('realizar-devolucion/<str:t_no>/', orden.realizar_devolucion , name="realizar_devolucion"),
    path('add-to-cart-reserva', cart.addtocartReserva, name="addtocartreserva"),

    path('reservar-libro', cart.RegistrarReserva , name="reservar_libro"),
    path('ver-reserva', cart.viewreserva , name="ver_reserva"),
    path('delete-reserva-item', cart.deletereservaitem, name="deletereservaitem"),

]

app/models.py
from ast import Delete
from distutils.command.upload import upload
from random import choices
from django.db import models
from django.contrib.auth.models import User
from multiselectfield import MultiSelectField
from django_countries.fields import CountryField
from django.core.validators import MaxValueValidator
from cities_light.models import Country, Region, City
from smart_selects.db_fields import ChainedForeignKey
# Create your models here.
GENEROS_PREFERENCIA = ((1, 'Accion'),
              (2, 'Aventura'),
              (3, 'Terror'),
              (4, 'Ciencia Ficcion'),
              (5, 'Romance'),
              (6, 'Humor'),
              (7, 'Poesia'),
              (8, 'Novela'))

DIAS_SEMANA = ((1, 'Lunes'),
              (2, 'Martes'),
              (3, 'Miercoles'),
              (4, 'Jueves'),
              (5, 'Viernes'),
              (6, 'Sabado'),
              (7, 'Domingo'))

class Editorial(models.Model):
    nombre = models.CharField(max_length=50)

    def __str__(self):
        return self.nombre

class Producto(models.Model):
    nombre =                models.CharField(max_length=50)
    precio =                models.IntegerField()
    autor =                 models.CharField(max_length=50)
    genero =                models.IntegerField(choices=GENEROS_PREFERENCIA)
    num_paginas=            models.IntegerField()
    descripcion =           models.TextField()
    nuevo =                 models.BooleanField()
    editorial =             models.ForeignKey(Editorial, on_delete=models.PROTECT)
    fecha_fabricacion =     models.DateField()
    issn=                   models.IntegerField(unique = True)
    imagen =                models.ImageField(upload_to="productos", null=True)
    quantity =              models.IntegerField(null=True)

    def __str__(self):
        return self.nombre

opciones_consulta =[
    [0, "consulta"],
    [1, "reclamo"],
    [2, "sugerencia"],
    [3, "felicitaciones"],
]
class Tienda (models.Model):
    nombre =                models.CharField(max_length=50)
    dias_atencion =         MultiSelectField(choices=DIAS_SEMANA,max_length=100)
    telefono =              models.IntegerField()
    horario_apertura =      models.TimeField()
    horario_cierre =        models.TimeField()

    def __str__(self):
        return self.nombre

class Carrito (models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    product = models.ForeignKey(Producto, on_delete = models.CASCADE)
    producto_qty = models.IntegerField(null=False, blank = False)
    created_at = models.DateTimeField(auto_now_add = True)

class Existencias(models.Model):
    producto = models.ForeignKey(Producto, on_delete = models.CASCADE)
    tienda = models.ForeignKey(Tienda, on_delete = models.CASCADE)
    existencias= models.IntegerField(null= True)


class Contacto(models.Model):
    nombre = models.CharField(max_length=50)
    correo = models.EmailField()
    tipo_consulta = models.IntegerField(choices=opciones_consulta)
    mensaje = models.TextField()
    avisos = models.BooleanField()

    def __str__(self):
        return self.nombre

GENEROS_PREFERENCIA = ((1, 'Accion'),
              (2, 'Aventura'),
              (3, 'Terror'),
              (4, 'Ciencia Ficcion'),
              (5, 'Romance'),
              (6, 'Humor'),
              (7, 'Poesia'),
              (8, 'Novela'))

GENERO =(
    (1, "Masculino"),
    (2, "Femenino"),
    (3, "No binario"),
)
class PerfilUsuario(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    DNI = models.PositiveIntegerField(primary_key=True, unique=True,validators=[MaxValueValidator(9999999999)])
    telefono = models.IntegerField()
    genero=models.IntegerField(choices=GENERO)
    fecha_nacimiento = models.DateField()
    pais = models.ForeignKey(Country, on_delete=models.CASCADE, null=True)
    departamento = ChainedForeignKey(Region, chained_field="pais", chained_model_field="country", null=True)
    ciudad = ChainedForeignKey(City, chained_field="departamento", chained_model_field="region", null=True)
    generos_preferencia = MultiSelectField(choices=GENEROS_PREFERENCIA,max_length=100,null=True,blank=True)
    direccion_correspondencia = models.CharField(max_length=100, null=True,blank=True)
    foto_perfil = models.ImageField(upload_to="fotoperfil", null=True, blank=True)

    def __str__(self):
        return self.user.username

class Tarjeta(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    num_tarjeta = models.IntegerField()
    nombre_propietario = models.CharField(max_length=50,null=True)
    mes_exp = models.IntegerField()
    year_exp = models.IntegerField()
    cvv = models.IntegerField()
    saldo = models.IntegerField()

class forum(models.Model):
    user= models.ForeignKey(User,on_delete=models.CASCADE, null=True)
    tema= models.CharField(max_length=300)
    descripcion = models.CharField(max_length=1000,blank=True)
    date_created=models.DateTimeField(auto_now_add=True,null=True)
    

class noticia(models.Model):
    producto=               models.ForeignKey(Producto, on_delete=models.CASCADE)
    descripcion =           models.TextField(null=True,blank=True)
    fecha_publicacion =     models.DateTimeField(auto_now_add=True, null=True)


#child model
class Discussion(models.Model):
    forum = models.ForeignKey(forum,blank=True,on_delete=models.CASCADE)
    discuss = models.CharField(max_length=1000)
    user= models.ForeignKey(User,on_delete=models.CASCADE, null=True)

class Orden(models.Model):
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    fname=models.CharField(max_length=150, null=True)
    lname=models.CharField(max_length=150, null=True)
    email=models.CharField(max_length=150, null=True)
    celular=models.CharField(max_length=150, null=True)
    direccion=models.TextField( null=True)
    pais=models.CharField(max_length=150, null=True)
    ciudad=models.CharField(max_length=150, null=True)
    dni=models.CharField(max_length=150, null=True)
    fecha_nacimiento=models.CharField(max_length=150, null=True)
    precio_total = models.FloatField(null=True)
    forma_pago = models.CharField(max_length=150, null=True)
    forma_pago_id = models.CharField(max_length=150, null=True)
    statusdeorden = {
        ('Pendiente','Pendiente'),
        ('En envio','En envio'),
        ('Completado','Completado'),
        ('Cancelada','Cancelada'),
        ('Devuelta','Devuelta'),
        
    }
    estatus = models.CharField(max_length=150,choices=statusdeorden,default ='Pendiente')
    mensaje =models.TextField( null=True)
    seguimiento_num = models.CharField(max_length=150, null=True)
    creado_en = models.DateTimeField(auto_now_add=True)
    actualizado_en = models.DateTimeField(auto_now=True)

    def __str__(self):
        return '{} - {}'.format(self.id, self.seguimiento_num)

class OrdenItem(models.Model):
    orden = models.ForeignKey(Orden, on_delete = models.CASCADE)
    producto =models.ForeignKey(Producto, on_delete = models.CASCADE)
    precio = models.FloatField(null=True)
    cantidad = models.IntegerField(null=True)

    def __str__(self):
        return '{} - {}'.format(self.orden.id, self.orden.seguimiento_num)

class Reserva(models.Model):
    product = models.ForeignKey(Producto, on_delete = models.CASCADE)
    user = models.ForeignKey(User, on_delete = models.CASCADE)
    cantidad_dias = models.SmallIntegerField('Cantidad de dias a reservar',default=1)
    fecha_creacion = models.DateField(auto_now_add=True)
    cantidad_producto= models.IntegerField(null=True)
    estado = models.BooleanField(default=True,verbose_name='Estado')

app/templates/app/producto/agregar.html
{% extends 'app/base.html' %}

{% block contenido %}

{% load crispy_forms_tags %}
<br>
<div class="row">
    <div class="col-12 col-md-6 offset-md-3">

        <div class="card">
            <div class="card-body">
                <h2>Agregar Libro</h2>
                <hr>
                <form action="" method="post" enctype="multipart/form-data">
                    {% csrf_token %}
                    <div class="inputBox">
                        <span>Nombre del Libro</span>
                        <input type="text" class="card-holder-input" id="nombre_libro"  name="nombre_libro" required>
                    </div>
                    <div class="inputBox">
                        <span>Precio</span>
                        <input type="number" class="card-number-input"  id="precio_libro"  name="precio_libro" required>
                    </div>
                    
                        <div class="inputBox">
                            <span>Autor</span>
                            <input type="text" class="card-holder-input" id="autor_libro"  name="autor_libro" required>
                        </div>
                        <div class="inputBox">
                            <label for="generos">Genero</label>
                            <select name="generos" id="generos" required>
                                <option value=1 >Accion</option>
                                <option value=2 >Aventura</option>
                                <option value=3 >Terror</option>
                                <option value=4 >Ciencia ficcion</option>
                                <option value=5 >Romance</option>
                                <option value=6 >Humor</option>
                                <option value=7 >Poesia</option>
                                <option value=8 >Novela</option>

                            </select>

                        </div>
                        <div class="inputBox">
                            <span>Numero de Paginas</span>
                            <input type="number" class="card-number-input"  id="num_paginas"  name="num_paginas" required>
                        </div>
                        <div class="inputBox">
                            <span>Descripcion</span>
                            <textarea type="text" class="card-number-input"  id="descripcion_libro"  name="descripcion_libro" required></textarea>
                        </div>
                        <div class="inputBox">
                            <span>¿Es nuevo?</span>
                            <input type="checkbox"   id="nuevo"  name="nuevo" >
                        </div>
                        <div class="col-md-6 mt-2">
                            <label>Editorial</label>
                            <select class="form-select form-select-lg mb-3" name="editorial_libro" aria-label=".form-select-lg example " required>
                                <label>Editorial</label>
                                {% for edi in editorial %}
                                    <option  value="{{ edi.nombre }}" class="form-control" >{{ edi.nombre }} </option>
                                {% endfor %}
                              </select>
                        </div>
                        <div class="inputBox">
                            <span>Fecha de publicacion</span>
                            <input type="date"   id="datePickerId"  name="fecha_fabricacion" required>
                        </div>
                        <div class="inputBox">
                            <span>ISSN</span>
                            <input type="number" class="card-number-input"  id="issn_libro"  name="issn_libro" required>
                        </div>
                    
                        <div class="inputBox">
                            <span>Cantidad</span>
                            <input type="number" class="card-number-input"  id="cantidad_libro"  name="cantidad_libro" required>
                        </div>
                </div>
                
            
                    <input type="submit" value="Añadir" class="submit-btn-btn-primary">
                    
                </form>
            {{ mensaje }}

        </div>
    </div>

  </div>
</div>
<style>
    .req {
    color: red;
    }
    
</style>
<script>
    datePickerId.max = new Date().toISOString().split("T")[0];
</script>
{% endblock %}

app/templates/app/producto/librodetalle.html
{% extends 'app/base.html' %}
{% load static %}

{% block js %}
<script src="{% static 'app/js/jquery-3.6.1.min.js' %}"></script>
<!--custom js-->
<script src="{% static 'app/js/menu.js' %}"></script>
{% endblock %}

{% block contenido %}
{% load humanize %}



<br>
<div class="container mt-5 mb-5">
    <div class="row d-flex justify-content-center">
        <div class="col-md-10">
            <div class="card product_data"> <!--SE AGREGÓ product data para hacer el carrito-->
                <div class="row">
                    <div class="col-md-5"> <!--ocupa 5/12 del container-->
                        {% if object.imagen %}
                        <div class="images p-4 pe-0">
                            <div class="text-center p-4"> <img src="{{ object.imagen.url }}" alt="imagen producto"/> </div>
                        </div>
                        {% endif %}
                    </div>
                    <div class="col-md-7"> <!--ocupa 7/12 del container-->
                        <div class="product p-4 "> 
                            <div class="mt-4 mb-3"> 
                                <h5>{{object.editorial | capfirst }}</h5>
                                <h1>{{object.nombre | title }}</h1>
                                <h4>{{object.autor | capfirst }}</h4>
                                <h3>$ {{object.precio | intcomma }}</h3>
                            </div>
                            <p class="about">{{object.descripcion | title }}</p>
                    

                           <!--  <div class="cart mt-4 align-items-center"> <button class="btn btn-danger text-uppercase mr-2 px-4 addToCartBtn">Añadir al carrito</button> </div> -->
                            {% if object.quantity > 0 %}
                                <label class="badge bg-success">Disponible</label>
                            {% else %}
                                <label class="badge bg-success">Agotado</label>
                            {% endif %}
                            {% if request.user.groups.all.0.name == "Cliente" %}
                            <div class="row mt-2">
                                <div class="col-md-3">

                                    {% csrf_token %}

                                    <input type="hidden" value="{{ object.id }}" class="prod_id"> <!--referencia a linea 36 de custom.js-->
                                    
                                    <label for="Quantity">Cantidad</label>
                                    <div class="input-group text-center" style="width:130px;">
                                        <button class="input-group-text decrement-btn">-</button>
                                        <input type="text" name="quantity" class="form-control qty-input text-center" value="1" onclick="update()"> <!--referencia a linea 37 de custom.js-->
                                        <button class="input-group-text increment-btn me-1" id="increment-btn">+</button>
                                    </div>
                                </div>
                                <div class="col-md-9">
                                    <br/>
                                    
                                    {% if object.quantity > 0 %}
                                        <button type="button" class="btn btn-danger text-uppercase me-3 ms-4 float-start px-3 addToCartBtn">Añadir al <i class="bi bi-cart-plus"></i> </button>
                                        <button type="button" class="btn btn-warning me-3 float-start reservarBtn">Reservar</button>

                                        {% endif %}
                                    {% endif %}
                                </div>
                            </div>

                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

app/templates/app/producto/listar.html
{% extends 'app/base.html' %}

{% block js %}

<script>
    function eliminarProducto(id){
        Swal.fire({
            "title" : "¿Estas seguro?",
            "text"  : "deseas eliminar el producto",
            "icon"  : "question",
            "showCancelButton" : true,
            "confirmButtonText" : "Confirmar",
            "cancelButtonText" : "Cancelar",
            "confirmButtonColor" : "#B90C0C"
        })
        .then(function(result){
            if(result.isConfirmed){
                window.location.href = "/eliminar-producto/"+id+"/"
            }
        })
    }
</script>

{% endblock %}

{% block contenido %}
{% load humanize %}
<br><br>
<div class="card">
    <div class="card-body">
        <h2>Listado de Libros</h2>
        <hr>
        <table class="table table-striped table-hover table-responsive-small">
            <tr>
                <th>Nombre</th>
                <th>Precio</th>
                <th>Editorial</th>
                <th>Unidades</th>
                <th>Opciones</th>
            </tr>
        
            {% for p in entity %}
        
            <tr>
                <td>{{ p.nombre | title }}</td>
                <td>$ {{p.precio | intcomma }}</td>
                <td>{{ p.editorial | title }}</td>
                <td>{{ p.quantity | intcomma }} </td>
                <td>
                    
                    {% if perms.app.change_producto %}
                    <a href="{% url 'modificar_producto' p.id %}" class="btn btn-primary">modificar</a>
                    {% endif %}

                    {% if perms.app.delete_producto %}
                    <a href="#" onclick="eliminarProducto({{ p.id }})" class="btn btn-danger">Eliminar</a>
                    {% endif %}
                </td>
            </tr>
        
            {% endfor %} 
        
        </table>
    </div>
    {% include 'app/paginator.html' %}
    {% if perms.app.change_producto %}
                    <a href="{% url 'agregar_producto' %}" class="btn btn-primary">Agregar Libro</a>
    {% endif %}
</div>



{% endblock %}

app/templates/app/producto/modificar.html
{% extends 'app/base.html' %}

{% block contenido %}

{% load crispy_forms_tags %}
<br>
<div class="row">
    <div class="col-12 col-md-6 offset-md-3">

        <div class="card">
            <div class="card-body">
                <h2>Editar Libro</h2>
                <hr>
            <form action="" method="post" enctype="multipart/form-data">

                {% csrf_token %}

                {{ form | crispy }}

                <br>
                <div class="d-flex justify-content-left">
                    <input type="submit" value="Editar" class="btn btn-primary">
                    &nbsp;
                    &nbsp;
                    &nbsp;
                    <input type="reset" value="Cancelar" class="btn btn-secondary">
                    

                </div>
                
            </form>
            {{ mensaje }}

        </div>
    </div>

  </div>
</div>

{% endblock %}